name:nyc_airbnb_dev
channels:
  -defaults
  -conda-forge
dependencies:
  -hydra-core
  -matplotlib-base
  -pandas
  -jupyterlab
  -pydantic
  -python=3.9
  -ydata-profiling
  -pip
  -pip:
      -mlflow
      -wandb
